---
- name: Show Information about target OS (on verbose)
  ansible.builtin.include_tasks:
    file: 'os_info.yml'

- name: Run simple versionscheck (optional)
  ansible.builtin.include_tasks:
    file: 'versioncheck.yml'
  when: packages__submodules_versioncheck | bool

- name: Adding additional apt sources (optional)
  ansible.builtin.include_tasks:
    file: 'sources_ethz.yml'
  when:
    - packages__adding_ethz | bool
    - ansible_architecture == 'x86_64'
    - ansible_distribution == 'Debian' and ansible_distribution_version | float >= 8
    - ansible_pkg_mgr == "apt"

- name: Install packages based on selection
  ansible.builtin.include_tasks:
    file: 'packages.yml'

- name: Upgrade all packages to latest
  become: true
  ansible.builtin.package:
    name: "*"
    state: "{{ base__package_state }}"
  when:
    - packages__upgrade_all | bool
